config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'statics#home'

  resources :users, except: [:show]
  resources :students
  resources :lessons
  resources :assistances, only: [:create]

  get '/students_menu' => "statics#students_menu"
  get '/lessons_menu' => "statics#lessons_menu"

  get '/lesson/:id/assistances' => "assistances#index", as: :lesson_assistances
  post '/assistances/absence' => "assistances#set_false_assistances"

end

app/models/concerns/lesson/students.rb
module Lesson::Students
  extend ActiveSupport::Concern
  included do
    def available_students
      Student.all
    end
  end
end

app/models/student.rb
class Student < ApplicationRecord
  validates :full_name, :uuid, :student_number, presence: true, uniqueness: true
  validates :full_name, length: { minimum: 6 }
  has_many :enrolled_students, dependent: :destroy
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  before_action :set_student, only: [:show, :edit, :update, :destroy]

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to students_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @student.update_attributes(student_params)
      redirect_to students_path
    else
      render 'edit'
    end
  end

  def destroy
    if @student.destroy
      redirect_to students_path
    else
      redirect_to root_path
    end
  end

  private

    def set_student
      @student = Student.find(params[:id])
    end

    def student_params
      params.require(:student).permit(:full_name, :uuid, :student_number)
    end
    
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>

  <%= render "shared/error_messages", :target => @student %>

  <div class="form-group">
    <%= f.label :nombre %>
    <%= f.text_field :full_name, autofocus: true, class: "form-control", required: true%>
  </div>

  <div class="form-group">
    <%= f.label :uuid, "UUID" %>
    <%= f.text_field :uuid, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :matricula %>
    <%= f.text_field :student_number, class: "form-control", required: true %>
  </div>

  <button type="submit" class="button-container-in-forms is-save ">Guardar</button>
  <%= link_to "Cancelar", students_path, class: "button-container-in-forms is-cancel"%>
<% end %>

app/views/students/_indextable.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Matrícula</th>
      <th>UUID</th>
      <th>Opciones</th>
    </tr>
  </thead>
  <tbody>
    <%= render @students %>
  </tbody>
</table>

app/views/students/_student.html.erb
<tr id="<%= student.id %>">
  <td><strong><%= student.full_name %></strong></td>
  <td><%= student.student_number %></td>
  <td><%= student.uuid %></td>
  <td>
    <%= link_to "", edit_student_path(student.id), class: "fa fa-pencil-square-o"%>
    <%= link_to "", {action: 'destroy', id: student.id},
          data: {confirm: "Seguro que desea eliminar al estudiante?"}, method: :delete,
          class: "fa fa-times destroy-student-icon"%>
  </td>
</tr>

app/views/students/edit.html.erb
<div class="title-section-container">
  <div>
    <i class="fa fa-pencil" aria-hidden="true"></i>
    Editar alumno: <%= @student.full_name%>
  </div>
</div>
<%= render 'form' %>

app/views/students/index.html.erb
<div class="title-section-container">
  <div>
    <i class="fa fa-reddit-alien" aria-hidden="true"></i>
    Alumnos
  </div>
</div>

<%= render "indextable" %>

<%= link_to new_student_path, class: "button-container" do%>
  <i class="fa fa-plus"></i>
  <div>Agregar nuevo alumno</div>
<% end %>

app/views/students/new.html.erb
<div class="title-section-container">
  <div>
    <i class="fa fa-plus" aria-hidden="true"></i>
    Nuevo alumno
  </div>
</div>
<%= render "form" %>