config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'statics#home'

  resources :users, except: [:show]
  resources :students
  resources :lessons
  resources :assistances, only: [:create]

  get '/students_menu' => "statics#students_menu"
  get '/lessons_menu' => "statics#lessons_menu"

  get '/lesson/:id/assistances' => "assistances#index", as: :lesson_assistances
  post '/assistances/absence' => "assistances#set_false_assistances"

end

app/models/concerns/lesson/users.rb
module Lesson::Users
  extend ActiveSupport::Concern
  included do
    def available_users
      User.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
   has_many :lessons
   validates :name,  presence: true
   validates :password, :password_confirmation, presence: true, length: {minimum: 5, maximum: 120}, on: :create
   validates :email, presence: true
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render 'new'
    end
  end

  def index
    @users = User.all.order(:last_name)
  end

  def edit
  end

  def update
    if @user.update_without_password(user_params)
      redirect_to users_path
    else
      puts @user.errors.full_messages
      redirect_to root_path
    end
  end

  def destroy
    if @user.destroy
      redirect_to users_path
    else
      redirect_to users_path
    end
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :last_name, :email, :password, :password_confirmation)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

  <%= render "shared/error_messages", :target => @user %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :name, autofocus: true, class: "form-control", required: true%>
  </div>
  <div class="form-group">
    <%= f.label :apellido %><br />
    <%= f.text_field :last_name, class: "form-control", required: true %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, class: "form-control", required: true%>
  </div>
  <div class="field">
    <%= f.label :contraseña %><br />
    <%= f.password_field :password, autofocus: true, class: "form-control", required: true%>
  </div>
  <div class="field">
    <%= f.label :confirmar_contraseña %><br />
    <%= f.password_field :password_confirmation, autofocus: true, class: "form-control", required: true%>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "Guardar", class: "button-container-in-forms is-save"%>
    <%= link_to "Cancelar", students_path, class: "button-container-in-forms is-cancel"%>
  </div>
<% end %>

app/views/users/_indextable.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Email</th>
      <th>Opciones</th>
    </tr>
  </thead>
  <tbody>
    <%= render @users %>
  </tbody>
</table>

app/views/users/_user.html.erb
<tr id="<%= user.id %>">
  <td><strong><%= user.name %></strong></td>
  <td><strong><%= user.last_name %></strong></td>
  <td><%= user.email %></td>
  <td>
    <%= link_to "", edit_user_path(user.id), class: "fa fa-pencil-square-o"%>
    <%= link_to "", {action: 'destroy', id: user.id},
          data: {confirm: "Seguro que desea eliminar al usuario?"}, method: :delete,
          class: "fa fa-times destroy-student-icon"%>
  </td>
</tr>

app/views/users/edit.html.erb
<div class="title-section-container">
  <div>
    <i class="fa fa-pencil" aria-hidden="true"></i>
    Editar al usuario: <%= @user.name %> <%= @user.last_name %>
  </div>
</div>

<%= render 'form' %>

app/views/users/index.html.erb
<div class="title-section-container">
  <div>
    <i class="fa fa-users" aria-hidden="true"></i>
    Usuarios
  </div>
</div>
<%= render "indextable" %>

<%= link_to new_user_path, class: "button-container" do%>
  <i class="fa fa-plus"></i>
  <div>Nuevo Usuario</div>
<% end %>

app/views/users/new.html.erb
<div class="title-section-container">
  <div>
    <i class="fa fa-plus" aria-hidden="true"></i>
    Nuevo usuario
  </div>
</div>
<%= render "form" %>