config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'statics#home'

  resources :users, except: [:show]
  resources :students
  resources :lessons
  resources :assistances, only: [:create]

  get '/students_menu' => "statics#students_menu"
  get '/lessons_menu' => "statics#lessons_menu"

  get '/lesson/:id/assistances' => "assistances#index", as: :lesson_assistances
  post '/assistances/absence' => "assistances#set_false_assistances"

end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController

  def home
    #Current user lessons
    @lessons = Lesson.where(user_id: current_user )
  end

  def students_menu
  end

end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/statics/_user_lessons.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Hora</th>
      <th>Salon</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @lessons.each do |lesson| %>
    <tr>
      <td><%= link_to lesson.name, lesson_path(lesson.id) %></td>
      <td><%= lesson.hour %></td>
      <td><%= lesson.classroom %></td>
      <td>
        <%= link_to "info", lesson_path(lesson) %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/statics/home.html.erb
<div class="title-section-container">
  <div>
    <i class="fa fa-user" aria-hidden="true"></i>
    Hola <%= current_user.name.capitalize %>
  </div>
</div>
<div class="subtitle-container">
  <div>Tus clases son: </div>
</div>
<%= render 'statics/user_lessons' %>

<%= link_to new_lesson_path, class: "button-container" do%>
  <i class="fa fa-plus"></i>
  <div>Agregar clase</div>
<% end %>

app/views/statics/lessons_menu.html.erb
<div class="title-section-container">
  <div>
    <i class="fa fa-folder-open" aria-hidden="true"></i>
    Clases
  </div>
</div>
<p>
  <%= link_to "Ver classes", lessons_path %>
</p>

<%= link_to new_lesson_path, class: "button-container" do%>
  <i class="fa fa-plus"></i>
  <div>Agregar nueva clase</div>
<% end %>

app/views/statics/students_menu.html.erb
<div class="title-section-container">
  <div>
    <i class="fa fa-reddit-alien" aria-hidden="true"></i>
    Alumnos
  </div>
</div>

<p>
  <%= link_to "Ver alumnos", students_path %>
</p>

<%= link_to new_student_path, class: "button-container" do%>
  <i class="fa fa-plus"></i>
  <div>Agregar nuevo alumno</div>
<% end %>