config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'statics#home'

  resources :users, except: [:show]
  resources :students
  resources :lessons
  resources :assistances, only: [:create]

  get '/students_menu' => "statics#students_menu"
  get '/lessons_menu' => "statics#lessons_menu"

  get '/lesson/:id/assistances' => "assistances#index", as: :lesson_assistances
  post '/assistances/absence' => "assistances#set_false_assistances"

end

app/models/concerns/lesson/enrolled_students.rb
module Lesson::EnrolledStudents
  extend ActiveSupport::Concern
  included do
    def available_enrolled_students
      enrolled_students = Student.all.map do |student|
        EnrolledStudent.new(student_id: student.id, lesson_id: self.id)
      end
    end
  end
end

app/models/concerns/lesson/students.rb
module Lesson::Students
  extend ActiveSupport::Concern
  included do
    def available_students
      Student.all
    end
  end
end

app/models/concerns/lesson/users.rb
module Lesson::Users
  extend ActiveSupport::Concern
  included do
    def available_users
      User.all
    end
  end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  include Lesson::Users
  include Lesson::Students
  include Lesson::EnrolledStudents
  validates :name, presence: true, uniqueness: true
  validates :classroom, :hour,  presence: true
  belongs_to :user
  delegate :name, to: :user, allow_nil: true, prefix: true
  delegate :last_name, to: :user, allow_nil: true, prefix: true
  # Pending relationships
  has_many :enrolled_students, dependent: :destroy
  accepts_nested_attributes_for :enrolled_students, allow_destroy: true, update_only: true

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  include Factories::LessonFactory
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  def index
    @lessons = Lesson.all
  end

  def new
    @lesson = Lesson.new
  end

  def create
    custom_params = custom_lesson_params_factory(lesson_params)
    @lesson = Lesson.new(custom_params)
    if @lesson.save
      redirect_to lessons_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @lesson.update_attributes(lesson_params)
      redirect_to lessons_path
    else
      render 'edit'
    end
  end

  def destroy
    if @lesson.destroy
      redirect_to lessons_path
    else
      redirect_to lessons_path
    end
  end

  private
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    def lesson_params
      params.require(:lesson).permit(:name, :hour, :classroom, :user_id,
        enrolled_students_attributes: [:id, :student_id, :is_valid, :lesson_id])
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_enrolled_students.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Matrícula</th>
      <th>Agregar</th>
    </tr>
  </thead>
  <tbody>
    <%= f.fields_for :enrolled_students, @lesson.available_enrolled_students do  |student| %>
      <tr id="<%= student.object.id %>">
        <th><%= student.object.student_full_name %></th>
        <th><%= student.object.student_student_number %></th>
        <input type="hidden" name="lesson[enrolled_students_attributes][<%= student.index %>][student_id]" value="<%=student.object.student_id %>"/>
        <input type="hidden" name="lesson[enrolled_students_attributes][<%= student.index %>][lesson_id]" value="<%= @lesson.try(:id) %>"/>
        <th><%= check_box_tag "lesson[enrolled_students_attributes][#{student.index}][is_valid]", student.object.id, false %></th>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/lessons/_form.html.erb
<%= form_for(@lesson) do |f| %>

  <%= render "shared/error_messages", :target => @lesson %>

  <div class="form-group">
    <%= f.label :nombre %>
    <%= f.text_field :name, autofocus: true, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= f.label "Hora: " %>
    <%= f.select :hour, HOURS, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= f.label "Salon: " %>
    <%= f.select :classroom, CLASSROOMS, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= f.label "Maestro: " %>
    <%= f.collection_select :user_id, @lesson.available_users, :id, :name,{required: true} %>
  </div>

  <div class="form-group">
    <div class="subtitle-container">
      <div>Alumnos </div>
    </div>
    <%= render partial: "lessons/enrolled_students", locals: {f: f} %>
  </div>

  <button type="submit" class="button-container-in-forms is-save ">Guardar</button>
  <%= link_to "Cancelar", lessons_path, class: "button-container-in-forms is-cancel"%>
<% end %>

app/views/lessons/_indextable.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Hora</th>
      <th>Salon</th>
      <th>Maestro</th>
      <th>Opciones</th>
      <th>Asistencias</th>
    </tr>
  </thead>
  <tbody>
    <%= render @lessons %>
  </tbody>
</table>

app/views/lessons/_lesson.html.erb
<tr id="<%= lesson.id %>">
  <td><%= link_to lesson.name, lesson_path(lesson), class: "blue-font" %></td>
  <td><%= lesson.hour %></td>
  <td><%= lesson.classroom %></td>
  <td><%= lesson.user_name %> <%= lesson.user_last_name %></td>
  <td>
    <%= link_to "", edit_lesson_path(lesson.id), class: "fa fa-pencil-square-o"%>
    <%= link_to "", {action: 'destroy', id: lesson.id},
          data: {confirm: "Seguro que desea eliminar la clase?"}, method: :delete,
          class: "fa fa-times destroy-student-icon"%>
  </td>
  <td><%= link_to "Asistencias", lesson_assistances_path(lesson.id), class: "blue-font" %></td>
</tr>

app/views/lessons/edit.html.erb
<div class="title-section-container">
  <div>
    <i class="fa fa-pencil" aria-hidden="true"></i>
    Editar clase: <%= @lesson.name %>
  </div>
</div>

<%= form_for(@lesson) do |f| %>

  <%= render "shared/error_messages", :target => @lesson %>

  <div class="form-group">
    <%= f.label :nombre %>
    <%= f.text_field :name, autofocus: true, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= f.label "Hora: " %>
    <%= f.select :hour, HOURS, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= f.label "Salón: " %>
    <%= f.select :classroom, CLASSROOMS, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= f.label "Maestro: " %>
    <%= f.collection_select :user_id, @lesson.available_users, :id, :name,{required: true} %>
  </div>

  <button type="submit" class="button-container-in-forms is-save ">Guardar</button>
  <%= link_to "Cancelar", lessons_path, class: "button-container-in-forms is-cancel"%>
<% end %>

app/views/lessons/index.html.erb
<div class="title-section-container">
  <div>
    <i class="fa fa-folder-open" aria-hidden="true"></i>
    Clases
  </div>
</div>
<%= render "indextable" %>

<%= link_to new_lesson_path, class: "button-container" do%>
  <i class="fa fa-plus"></i>
  <div>Agregar nueva clase</div>
<% end %>

app/views/lessons/new.html.erb
<div class="title-section-container">
  <div>
    <i class="fa fa-plus" aria-hidden="true"></i>
    Nueva clase
  </div>
</div>
<%= render "form" %>

app/views/lessons/show.html.erb
<h3><strong>Clase:</strong> <%= @lesson.name %></h3>

<h4><strong>Hora:</strong> <%= @lesson.hour %></h4>

<h4><strong>Salón:</strong> <%= @lesson.classroom %></h4>

<h4><strong>Maestro</strong> <%= @lesson.user_name %></h4>

<div class="back-button-row">
  <%= link_to lesson_assistances_path(@lesson.id), class: "back-button" do %>
    Asistencias
  <% end %>
</div>

<br>
<h4>Alumnos</h4>
<table>
  <table class="table">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Matrícula</th>
      </tr>
    </thead>
    <tbody>
      <% @lesson.enrolled_students.each do |enrolled_student| %>
        <tr>
          <th><%= enrolled_student.student_full_name %></th>
          <th><%= enrolled_student.student_student_number %></th>
        </tr>
      <% end %>
    </tbody>
  </table>
</table>
<div class="back-button-row">
  <%= link_to lessons_path, class: "back-button" do %>
    <i class="fa fa-arrow-left"></i>
    Regresar
  <% end %>
</div>